version: "2.1"

services:
    nginx:
        build: ./nginx/
        container_name: rest_order_app_nginx
        dns_search: nginx
        ports:
            - 8080:80
        volumes:
            - "./codebase:/var/www/html:ro"
        links:
            - php
            - mysql
        depends_on:
            - composer
    php:
        build: ./php/
        container_name: rest_order_app_php
        expose:
            - 9000
        volumes:
            - "./codebase:/var/www/html"
        working_dir: /var/www/html
        dns_search: php
        depends_on:
            - mysql
        dns:
            - 8.8.8.8
            - 4.4.4.4
    mysql:
        build: ./mysql/
        container_name: rest_order_app_mysql
        ports:
            - 3306:3306
        dns_search: mysql
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "orderapp"
        restart: always


    composer:
        container_name: rest_order_app_composer
        restart: 'no'
        image: koutsoumpos89/composer-php7.1
        command: install --ignore-platform-reqs
        working_dir: /var/www/html
        volumes:
            - "./codebase:/var/www/html"

volumes:
    db-data:
      driver: local

